# Name of the environment
name: big-data-solutions-development-deployment

# Channels to search for packages
channels: [conda-forge, defaults]

# List of package dependencies
dependencies:
  - python=3.12
  - pip=25.2
  - pyspark=4.0.1
  - jupyterlab=4.4.7
  - pyarrow=21.0.0
  - great-expectations=1.5.11
  - requests=2.32.5
  # Additional packages via pip
  - pip:
    - mlflow==3.3.2
